Name: anycubicslicernext
Version: 1.3.9.4
Release: 1
Summary: Anycubic Slicer is an open source slicer for FDM printers
License: see %{_datadir}/doc/anycubicslicernext/copyright
Distribution: Debian
Group: Converted/utils
Source0: %{name}-%{version}.tar.bz2

%description
Anycubic Slicer is an open source slicer for FDM printers

(Converted from a deb package by alien version 8.95.)

%define debug_package %{nil}

%prep
%setup -q

%build

%install
pwd
mv -v ./usr %{buildroot}

%files
%dir %{_datadir}/AnycubicSlicerNext/
%{_bindir}/AnycubicSlicerNext
%{_libdir}/libcloud_mqtt.so
%{_libdir}/libcloud_sdk_cpp.so
%{_libdir}/libcommon_encrypt.so
%{_libdir}/libcommon_httpClient.a
%{_libdir}/libcommon_log.so
%{_libdir}/libcommon_utils.a
%{_libdir}/libcompress.so
%{_libdir}/libmach_mqtt.so
%{_libdir}/libMachMQTT.so
%{_libdir}/libmqtt_client.so
%{_libdir}/libRequestFilter.so
%{_libdir}/libssdplib.so
%{_libdir}/libWorkbench.so
%{_datadir}/AnycubicSlicerNext/resources/AnycubicSlicer.icns
%{_datadir}/AnycubicSlicerNext/resources/build-timestamp.txt
%{_datadir}/AnycubicSlicerNext/resources/build-version.txt
%{_datadir}/AnycubicSlicerNext/resources/calib/filament_flow/flowrate-test-pass1.3mf
%{_datadir}/AnycubicSlicerNext/resources/calib/filament_flow/flowrate-test-pass2.3mf
%{_datadir}/AnycubicSlicerNext/resources/calib/filament_flow/Orca-LinearFlow.3mf
%{_datadir}/AnycubicSlicerNext/resources/calib/filament_flow/Orca-LinearFlow_fine.3mf
%{_datadir}/AnycubicSlicerNext/resources/calib/filament_flow/pass1.3mf
%{_datadir}/AnycubicSlicerNext/resources/calib/pressure_advance/pa_pattern.3mf
%{_datadir}/AnycubicSlicerNext/resources/calib/pressure_advance/pressure_advance_test.stl
%{_datadir}/AnycubicSlicerNext/resources/calib/pressure_advance/tower_with_seam.stl
%{_datadir}/AnycubicSlicerNext/resources/calib/retraction/retraction_tower.stl
%{_datadir}/AnycubicSlicerNext/resources/calib/temperature_tower/temperature_tower.stl
%{_datadir}/AnycubicSlicerNext/resources/calib/tolerance_test/OrcaToleranceTest.stl
%{_datadir}/AnycubicSlicerNext/resources/calib/vfa/VFA.stl
%{_datadir}/AnycubicSlicerNext/resources/calib/volumetric_speed/SpeedTestStructure.step
%{_datadir}/AnycubicSlicerNext/resources/calib/volumetric_speed/SpeedTestStructure.stp
%{_datadir}/AnycubicSlicerNext/resources/cert/printer.cer
%{_datadir}/AnycubicSlicerNext/resources/cert/slicer_base64.cer
%{_datadir}/AnycubicSlicerNext/resources/check_access_code.txt
%{_datadir}/AnycubicSlicerNext/resources/cloud/cloud_profile.ini
%{_datadir}/AnycubicSlicerNext/resources/cloud/pingying.txt
%{_datadir}/AnycubicSlicerNext/resources/dailytip/index.html
%{_datadir}/AnycubicSlicerNext/resources/data/hints.ini
%{_datadir}/AnycubicSlicerNext/resources/debugTimeStamp.txt
%{_datadir}/AnycubicSlicerNext/resources/flush/flush_data.txt
%{_datadir}/AnycubicSlicerNext/resources/fonts/HarmonyOS_Sans_SC_Bold.ttf
%{_datadir}/AnycubicSlicerNext/resources/fonts/HarmonyOS_Sans_SC_Regular.ttf
%{_datadir}/AnycubicSlicerNext/resources/fonts/NanumGothic-Bold.ttf
%{_datadir}/AnycubicSlicerNext/resources/fonts/NanumGothic-Regular.ttf
%{_datadir}/AnycubicSlicerNext/resources/fonts/NotoSansKR-Bold.ttf
%{_datadir}/AnycubicSlicerNext/resources/fonts/NotoSansKR-Regular.ttf
%{_datadir}/AnycubicSlicerNext/resources/fonts/OFL.txt
%{_datadir}/AnycubicSlicerNext/resources/handy_models/*
%{_datadir}/AnycubicSlicerNext/resources/i18n/ca/AnycubicSlicer.mo
%{_datadir}/AnycubicSlicerNext/resources/i18n/cs/AnycubicSlicer.mo
%{_datadir}/AnycubicSlicerNext/resources/i18n/de/AnycubicSlicer.mo
%{_datadir}/AnycubicSlicerNext/resources/i18n/en/AnycubicSlicer.mo
%{_datadir}/AnycubicSlicerNext/resources/i18n/es/AnycubicSlicer.mo
%{_datadir}/AnycubicSlicerNext/resources/i18n/fr/AnycubicSlicer.mo
%{_datadir}/AnycubicSlicerNext/resources/i18n/hu/AnycubicSlicer.mo
%{_datadir}/AnycubicSlicerNext/resources/i18n/it/AnycubicSlicer.mo
%{_datadir}/AnycubicSlicerNext/resources/i18n/ja/AnycubicSlicer.mo
%{_datadir}/AnycubicSlicerNext/resources/i18n/ko/AnycubicSlicer.mo
%{_datadir}/AnycubicSlicerNext/resources/i18n/nl/AnycubicSlicer.mo
%{_datadir}/AnycubicSlicerNext/resources/i18n/placeholder.txt
%{_datadir}/AnycubicSlicerNext/resources/i18n/pl/AnycubicSlicer.mo
%{_datadir}/AnycubicSlicerNext/resources/i18n/pt_BR/AnycubicSlicer.mo
%{_datadir}/AnycubicSlicerNext/resources/i18n/ru/AnycubicSlicer.mo
%{_datadir}/AnycubicSlicerNext/resources/i18n/sv/AnycubicSlicer.mo
%{_datadir}/AnycubicSlicerNext/resources/i18n/tr/AnycubicSlicer.mo
%{_datadir}/AnycubicSlicerNext/resources/i18n/uk/AnycubicSlicer.mo
%{_datadir}/AnycubicSlicerNext/resources/i18n/zh_CN/AnycubicSlicer.mo
%{_datadir}/AnycubicSlicerNext/resources/i18n/zh_TW/AnycubicSlicer.mo
%{_datadir}/AnycubicSlicerNext/resources/images/*
%{_datadir}/AnycubicSlicerNext/resources/info/filament_info.json
%{_datadir}/AnycubicSlicerNext/resources/info/nozzle_info.json
%{_datadir}/AnycubicSlicerNext/resources/printers/ams_load.gcode
%{_datadir}/AnycubicSlicerNext/resources/printers/ams_unload.gcode
%{_datadir}/AnycubicSlicerNext/resources/printers/BL-P001.json
%{_datadir}/AnycubicSlicerNext/resources/printers/BL-P002.json
%{_datadir}/AnycubicSlicerNext/resources/printers/C11.json
%{_datadir}/AnycubicSlicerNext/resources/printers/C12.json
%{_datadir}/AnycubicSlicerNext/resources/printers/C13.json
%{_datadir}/AnycubicSlicerNext/resources/printers/filaments_blacklist.json
%{_datadir}/AnycubicSlicerNext/resources/printers/N1.json
%{_datadir}/AnycubicSlicerNext/resources/printers/N2S.json
%{_datadir}/AnycubicSlicerNext/resources/printers/version.txt
%{_datadir}/AnycubicSlicerNext/resources/profiles/Anycubic/*.stl
%{_datadir}/AnycubicSlicerNext/resources/profiles/Anycubic/*.png
%{_datadir}/AnycubicSlicerNext/resources/profiles/Anycubic/*.svg
%{_datadir}/AnycubicSlicerNext/resources/profiles/Anycubic/filament/*
%{_datadir}/AnycubicSlicerNext/resources/profiles/Anycubic.json
%{_datadir}/AnycubicSlicerNext/resources/profiles/Anycubic/machine/*
%{_datadir}/AnycubicSlicerNext/resources/profiles/Anycubic/process/*
%{_datadir}/AnycubicSlicerNext/resources/profiles_template/Template/filament/filament_abs_template.json
%{_datadir}/AnycubicSlicerNext/resources/profiles_template/Template/filament/filament_asa_template.json
%{_datadir}/AnycubicSlicerNext/resources/profiles_template/Template/filament/filament_hips_template.json
%{_datadir}/AnycubicSlicerNext/resources/profiles_template/Template/filament/filament_pa_template.json
%{_datadir}/AnycubicSlicerNext/resources/profiles_template/Template/filament/filament_pc_template.json
%{_datadir}/AnycubicSlicerNext/resources/profiles_template/Template/filament/filament_petg_template.json
%{_datadir}/AnycubicSlicerNext/resources/profiles_template/Template/filament/filament_pla_template.json
%{_datadir}/AnycubicSlicerNext/resources/profiles_template/Template/filament/filament_ppa_template.json
%{_datadir}/AnycubicSlicerNext/resources/profiles_template/Template/filament/filament_pps_template.json
%{_datadir}/AnycubicSlicerNext/resources/profiles_template/Template/filament/filament_pva_template.json
%{_datadir}/AnycubicSlicerNext/resources/profiles_template/Template/filament/filament_sbs_template.json
%{_datadir}/AnycubicSlicerNext/resources/profiles_template/Template/filament/filament_tpu_template.json
%{_datadir}/AnycubicSlicerNext/resources/profiles_template/Template.json
%{_datadir}/AnycubicSlicerNext/resources/profiles_template/Template/process/*
%{_datadir}/AnycubicSlicerNext/resources/shaders/110/background.fs
%{_datadir}/AnycubicSlicerNext/resources/shaders/110/background.vs
%{_datadir}/AnycubicSlicerNext/resources/shaders/110/flat_clip.fs
%{_datadir}/AnycubicSlicerNext/resources/shaders/110/flat_clip.vs
%{_datadir}/AnycubicSlicerNext/resources/shaders/110/flat.fs
%{_datadir}/AnycubicSlicerNext/resources/shaders/110/flat_texture.fs
%{_datadir}/AnycubicSlicerNext/resources/shaders/110/flat_texture.vs
%{_datadir}/AnycubicSlicerNext/resources/shaders/110/flat.vs
%{_datadir}/AnycubicSlicerNext/resources/shaders/110/gouraud.fs
%{_datadir}/AnycubicSlicerNext/resources/shaders/110/gouraud_light.fs
%{_datadir}/AnycubicSlicerNext/resources/shaders/110/gouraud_light_instanced.fs
%{_datadir}/AnycubicSlicerNext/resources/shaders/110/gouraud_light_instanced.vs
%{_datadir}/AnycubicSlicerNext/resources/shaders/110/gouraud_light.vs
%{_datadir}/AnycubicSlicerNext/resources/shaders/110/gouraud.vs
%{_datadir}/AnycubicSlicerNext/resources/shaders/110/imgui.fs
%{_datadir}/AnycubicSlicerNext/resources/shaders/110/imgui.vs
%{_datadir}/AnycubicSlicerNext/resources/shaders/110/mm_contour.fs
%{_datadir}/AnycubicSlicerNext/resources/shaders/110/mm_contour.vs
%{_datadir}/AnycubicSlicerNext/resources/shaders/110/mm_gouraud.fs
%{_datadir}/AnycubicSlicerNext/resources/shaders/110/mm_gouraud.vs
%{_datadir}/AnycubicSlicerNext/resources/shaders/110/printbed.fs
%{_datadir}/AnycubicSlicerNext/resources/shaders/110/printbed.vs
%{_datadir}/AnycubicSlicerNext/resources/shaders/110/thumbnail.fs
%{_datadir}/AnycubicSlicerNext/resources/shaders/110/thumbnail.vs
%{_datadir}/AnycubicSlicerNext/resources/shaders/110/variable_layer_height.fs
%{_datadir}/AnycubicSlicerNext/resources/shaders/110/variable_layer_height.vs
%{_datadir}/AnycubicSlicerNext/resources/shaders/140/background.fs
%{_datadir}/AnycubicSlicerNext/resources/shaders/140/background.vs
%{_datadir}/AnycubicSlicerNext/resources/shaders/140/flat_clip.fs
%{_datadir}/AnycubicSlicerNext/resources/shaders/140/flat_clip.vs
%{_datadir}/AnycubicSlicerNext/resources/shaders/140/flat.fs
%{_datadir}/AnycubicSlicerNext/resources/shaders/140/flat_texture.fs
%{_datadir}/AnycubicSlicerNext/resources/shaders/140/flat_texture.vs
%{_datadir}/AnycubicSlicerNext/resources/shaders/140/flat.vs
%{_datadir}/AnycubicSlicerNext/resources/shaders/140/gouraud.fs
%{_datadir}/AnycubicSlicerNext/resources/shaders/140/gouraud_light.fs
%{_datadir}/AnycubicSlicerNext/resources/shaders/140/gouraud_light_instanced.fs
%{_datadir}/AnycubicSlicerNext/resources/shaders/140/gouraud_light_instanced.vs
%{_datadir}/AnycubicSlicerNext/resources/shaders/140/gouraud_light.vs
%{_datadir}/AnycubicSlicerNext/resources/shaders/140/gouraud.vs
%{_datadir}/AnycubicSlicerNext/resources/shaders/140/imgui.fs
%{_datadir}/AnycubicSlicerNext/resources/shaders/140/imgui.vs
%{_datadir}/AnycubicSlicerNext/resources/shaders/140/mm_contour.fs
%{_datadir}/AnycubicSlicerNext/resources/shaders/140/mm_contour.vs
%{_datadir}/AnycubicSlicerNext/resources/shaders/140/mm_gouraud.fs
%{_datadir}/AnycubicSlicerNext/resources/shaders/140/mm_gouraud.vs
%{_datadir}/AnycubicSlicerNext/resources/shaders/140/printbed.fs
%{_datadir}/AnycubicSlicerNext/resources/shaders/140/printbed.vs
%{_datadir}/AnycubicSlicerNext/resources/shaders/140/thumbnail.fs
%{_datadir}/AnycubicSlicerNext/resources/shaders/140/thumbnail.vs
%{_datadir}/AnycubicSlicerNext/resources/shaders/140/variable_layer_height.fs
%{_datadir}/AnycubicSlicerNext/resources/shaders/140/variable_layer_height.vs
%{_datadir}/AnycubicSlicerNext/resources/tooltip/main.css
%{_datadir}/AnycubicSlicerNext/resources/tooltip/main.js
%{_datadir}/AnycubicSlicerNext/resources/tooltip/.md
%{_datadir}/AnycubicSlicerNext/resources/tooltip/privacyupdate.html
%{_datadir}/AnycubicSlicerNext/resources/tooltip/releasenote.html
%{_datadir}/AnycubicSlicerNext/resources/tooltip/styled.html
%{_datadir}/AnycubicSlicerNext/resources/tooltip/zh_CN/.md
%{_datadir}/AnycubicSlicerNext/resources/web/anycubic/anycubic_workbench.html
%{_datadir}/AnycubicSlicerNext/resources/web/anycubic/css/dark.css
%{_datadir}/AnycubicSlicerNext/resources/web/anycubic/css/home.css
%{_datadir}/AnycubicSlicerNext/resources/web/anycubic/missing_connection.html
%{_datadir}/AnycubicSlicerNext/resources/web/anycubic/setup_connection.png
%{_datadir}/AnycubicSlicerNext/resources/web/anycubic/test.html
%{_datadir}/AnycubicSlicerNext/resources/web/data/text.js
%{_datadir}/AnycubicSlicerNext/resources/web/guide/11/11.css
%{_datadir}/AnycubicSlicerNext/resources/web/guide/11/11.js
%{_datadir}/AnycubicSlicerNext/resources/web/guide/1/1.css
%{_datadir}/AnycubicSlicerNext/resources/web/guide/11/index.html
%{_datadir}/AnycubicSlicerNext/resources/web/guide/1/1.js
%{_datadir}/AnycubicSlicerNext/resources/web/guide/11/location.png
%{_datadir}/AnycubicSlicerNext/resources/web/guide/1/index.html
%{_datadir}/AnycubicSlicerNext/resources/web/guide/21/21.css
%{_datadir}/AnycubicSlicerNext/resources/web/guide/21/21.js
%{_datadir}/AnycubicSlicerNext/resources/web/guide/21/index.html
%{_datadir}/AnycubicSlicerNext/resources/web/guide/21/test.js
%{_datadir}/AnycubicSlicerNext/resources/web/guide/22/22.css
%{_datadir}/AnycubicSlicerNext/resources/web/guide/22/22.js
%{_datadir}/AnycubicSlicerNext/resources/web/guide/22/index.html
%{_datadir}/AnycubicSlicerNext/resources/web/guide/22/test.js
%{_datadir}/AnycubicSlicerNext/resources/web/guide/23/23.css
%{_datadir}/AnycubicSlicerNext/resources/web/guide/23/23.js
%{_datadir}/AnycubicSlicerNext/resources/web/guide/23/index.html
%{_datadir}/AnycubicSlicerNext/resources/web/guide/24/24.css
%{_datadir}/AnycubicSlicerNext/resources/web/guide/24/24.js
%{_datadir}/AnycubicSlicerNext/resources/web/guide/24/index.html
%{_datadir}/AnycubicSlicerNext/resources/web/guide/31/31.css
%{_datadir}/AnycubicSlicerNext/resources/web/guide/31/31.js
%{_datadir}/AnycubicSlicerNext/resources/web/guide/31/index.html
%{_datadir}/AnycubicSlicerNext/resources/web/guide/3/3.css
%{_datadir}/AnycubicSlicerNext/resources/web/guide/3/3.js
%{_datadir}/AnycubicSlicerNext/resources/web/guide/3/index.html
%{_datadir}/AnycubicSlicerNext/resources/web/guide/5/5.css
%{_datadir}/AnycubicSlicerNext/resources/web/guide/5/5.js
%{_datadir}/AnycubicSlicerNext/resources/web/guide/5/index.html
%{_datadir}/AnycubicSlicerNext/resources/web/guide/6/6.css
%{_datadir}/AnycubicSlicerNext/resources/web/guide/6/6.js
%{_datadir}/AnycubicSlicerNext/resources/web/guide/6/index.html
%{_datadir}/AnycubicSlicerNext/resources/web/guide/6/restart.png
%{_datadir}/AnycubicSlicerNext/resources/web/guide/css/common.css
%{_datadir}/AnycubicSlicerNext/resources/web/guide/css/dark.css
%{_datadir}/AnycubicSlicerNext/resources/web/guide/css/home.css
%{_datadir}/AnycubicSlicerNext/resources/web/guide/css/test.css
%{_datadir}/AnycubicSlicerNext/resources/web/guide/index.html
%{_datadir}/AnycubicSlicerNext/resources/web/guide/js/common.js
%{_datadir}/AnycubicSlicerNext/resources/web/guide/js/home.js
%{_datadir}/AnycubicSlicerNext/resources/web/homepage/css/dark.css
%{_datadir}/AnycubicSlicerNext/resources/web/homepage/css/homebody.css
%{_datadir}/AnycubicSlicerNext/resources/web/homepage/css/init.css
%{_datadir}/AnycubicSlicerNext/resources/web/homepage/css/leftmenu.css
%{_datadir}/AnycubicSlicerNext/resources/web/homepage/css/light.css
%{_datadir}/AnycubicSlicerNext/resources/web/homepage/css/online.css
%{_datadir}/AnycubicSlicerNext/resources/web/homepage/css/recent.css
%{_datadir}/AnycubicSlicerNext/resources/web/homepage/disconnect.html
%{_datadir}/AnycubicSlicerNext/resources/web/homepage/homebody.html
%{_datadir}/AnycubicSlicerNext/resources/web/homepage/img/*
%{_datadir}/AnycubicSlicerNext/resources/web/homepage/js/account.js
%{_datadir}/AnycubicSlicerNext/resources/web/homepage/js/homebody.js
%{_datadir}/AnycubicSlicerNext/resources/web/homepage/js/home.js
%{_datadir}/AnycubicSlicerNext/resources/web/homepage/js/host_application.js
%{_datadir}/AnycubicSlicerNext/resources/web/homepage/js/leftmenu.js
%{_datadir}/AnycubicSlicerNext/resources/web/homepage/js/sensorsdata.js
%{_datadir}/AnycubicSlicerNext/resources/web/homepage/js/test.js
%{_datadir}/AnycubicSlicerNext/resources/web/homepage/leftmenu.html
%{_datadir}/AnycubicSlicerNext/resources/web/homepage/test.html
%{_datadir}/AnycubicSlicerNext/resources/web/image/edit.svg
%{_datadir}/AnycubicSlicerNext/resources/web/image/logo2.png
%{_datadir}/AnycubicSlicerNext/resources/web/image/logo.png
%{_datadir}/AnycubicSlicerNext/resources/web/include/globalapi.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/jquery-2.1.1.min.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/jquery-3.6.0.min.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/json2.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/angular/angular/src/public-api.d.ts
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/angular/angular/src/swiper.component.d.ts
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/angular/angular/src/swiper.module.d.ts
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/angular/angular/src/swiper-slide.directive.d.ts
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/angular/angular/src/utils/get-params.d.ts
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/angular/angular/src/utils/params-list.d.ts
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/angular/angular/src/utils/utils.d.ts
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/angular/bundles/swiper_angular.umd.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/angular/bundles/swiper_angular.umd.js.map
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/angular/esm2015/angular/src/public-api.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/angular/esm2015/angular/src/swiper.component.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/angular/esm2015/angular/src/swiper.module.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/angular/esm2015/angular/src/swiper-slide.directive.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/angular/esm2015/angular/src/utils/get-params.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/angular/esm2015/angular/src/utils/params-list.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/angular/esm2015/angular/src/utils/utils.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/angular/esm2015/swiper-angular.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/angular/esm2015/swiper_angular.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/angular/fesm2015/swiper_angular.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/angular/fesm2015/swiper_angular.js.map
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/angular/package.json
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/angular/swiper-angular.d.ts
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/angular/swiper_angular.d.ts
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/core/breakpoints/getBreakpoint.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/core/breakpoints/index.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/core/breakpoints/setBreakpoint.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/core/check-overflow/index.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/core/classes/addClasses.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/core/classes/index.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/core/classes/removeClasses.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/core/core.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/core/defaults.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/core/events-emitter.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/core/events/index.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/core/events/onClick.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/core/events/onResize.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/core/events/onScroll.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/core/events/onTouchEnd.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/core/events/onTouchMove.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/core/events/onTouchStart.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/core/grab-cursor/index.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/core/grab-cursor/setGrabCursor.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/core/grab-cursor/unsetGrabCursor.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/core/images/index.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/core/images/loadImage.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/core/images/preloadImages.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/core/loop/index.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/core/loop/loopCreate.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/core/loop/loopDestroy.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/core/loop/loopFix.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/core/moduleExtendParams.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/core/modules/observer/observer.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/core/modules/resize/resize.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/core/slide/index.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/core/slide/slideNext.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/core/slide/slidePrev.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/core/slide/slideReset.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/core/slide/slideToClickedSlide.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/core/slide/slideToClosest.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/core/slide/slideTo.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/core/slide/slideToLoop.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/core/transition/index.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/core/transition/setTransition.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/core/transition/transitionEmit.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/core/transition/transitionEnd.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/core/transition/transitionStart.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/core/translate/getTranslate.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/core/translate/index.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/core/translate/maxTranslate.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/core/translate/minTranslate.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/core/translate/setTranslate.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/core/translate/translateTo.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/core/update/index.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/core/update/updateActiveIndex.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/core/update/updateAutoHeight.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/core/update/updateClickedSlide.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/core/update/updateProgress.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/core/update/updateSize.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/core/update/updateSlidesClasses.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/core/update/updateSlides.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/core/update/updateSlidesOffset.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/core/update/updateSlidesProgress.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/LICENSE
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/a11y/a11y.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/a11y/a11y.less
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/a11y/a11y.min.css
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/a11y/a11y.scss
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/autoplay/autoplay.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/autoplay/autoplay.less
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/autoplay/autoplay.min.css
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/autoplay/autoplay.scss
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/controller/controller.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/controller/controller.less
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/controller/controller.min.css
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/controller/controller.scss
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/effect-cards/effect-cards.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/effect-cards/effect-cards.less
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/effect-cards/effect-cards.min.css
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/effect-cards/effect-cards.scss
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/effect-coverflow/effect-coverflow.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/effect-coverflow/effect-coverflow.less
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/effect-coverflow/effect-coverflow.min.css
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/effect-coverflow/effect-coverflow.scss
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/effect-creative/effect-creative.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/effect-creative/effect-creative.less
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/effect-creative/effect-creative.min.css
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/effect-creative/effect-creative.scss
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/effect-cube/effect-cube.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/effect-cube/effect-cube.less
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/effect-cube/effect-cube.min.css
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/effect-cube/effect-cube.scss
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/effect-fade/effect-fade.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/effect-fade/effect-fade.less
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/effect-fade/effect-fade.min.css
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/effect-fade/effect-fade.scss
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/effect-flip/effect-flip.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/effect-flip/effect-flip.less
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/effect-flip/effect-flip.min.css
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/effect-flip/effect-flip.scss
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/free-mode/free-mode.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/free-mode/free-mode.less
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/free-mode/free-mode.min.css
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/free-mode/free-mode.scss
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/grid/grid.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/grid/grid.less
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/grid/grid.min.css
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/grid/grid.scss
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/hash-navigation/hash-navigation.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/hash-navigation/hash-navigation.less
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/hash-navigation/hash-navigation.min.css
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/hash-navigation/hash-navigation.scss
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/history/history.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/history/history.less
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/history/history.min.css
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/history/history.scss
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/keyboard/keyboard.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/keyboard/keyboard.less
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/keyboard/keyboard.min.css
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/keyboard/keyboard.scss
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/lazy/lazy.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/lazy/lazy.less
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/lazy/lazy.min.css
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/lazy/lazy.scss
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/manipulation/manipulation.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/manipulation/manipulation.less
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/manipulation/manipulation.min.css
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/manipulation/manipulation.scss
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/manipulation/methods/addSlide.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/manipulation/methods/appendSlide.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/manipulation/methods/prependSlide.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/manipulation/methods/removeAllSlides.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/manipulation/methods/removeSlide.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/mousewheel/mousewheel.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/mousewheel/mousewheel.less
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/mousewheel/mousewheel.min.css
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/mousewheel/mousewheel.scss
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/navigation/navigation.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/navigation/navigation.less
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/navigation/navigation.min.css
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/navigation/navigation.scss
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/pagination/pagination.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/pagination/pagination.less
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/pagination/pagination.min.css
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/pagination/pagination.scss
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/parallax/parallax.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/parallax/parallax.less
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/parallax/parallax.min.css
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/parallax/parallax.scss
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/scrollbar/scrollbar.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/scrollbar/scrollbar.less
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/scrollbar/scrollbar.min.css
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/scrollbar/scrollbar.scss
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/thumbs/thumbs.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/thumbs/thumbs.less
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/thumbs/thumbs.min.css
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/thumbs/thumbs.scss
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/virtual/virtual.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/virtual/virtual.less
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/virtual/virtual.min.css
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/virtual/virtual.scss
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/zoom/zoom.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/zoom/zoom.less
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/zoom/zoom.min.css
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/modules/zoom/zoom.scss
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/node_modules/dom7/dom7.d.ts
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/node_modules/dom7/dom7.esm.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/node_modules/dom7/dom7.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/node_modules/dom7/dom7.js.map
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/node_modules/dom7/dom7.min.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/node_modules/dom7/dom7.min.js.map
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/node_modules/dom7/LICENSE
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/node_modules/dom7/package.json
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/node_modules/dom7/README.md
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/node_modules/ssr-window/LICENSE
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/node_modules/ssr-window/package.json
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/node_modules/ssr-window/README.md
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/node_modules/ssr-window/ssr-window.esm.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/node_modules/ssr-window/ssr-window.umd.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/node_modules/ssr-window/ssr-window.umd.js.map
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/node_modules/ssr-window/ssr-window.umd.min.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/node_modules/ssr-window/ssr-window.umd.min.js.map
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/node_modules/ssr-window/types/document.d.ts
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/node_modules/ssr-window/types/extend.d.ts
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/node_modules/ssr-window/types/ssr-window.d.ts
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/node_modules/ssr-window/types/window.d.ts
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/package.json
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/postinstall.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/react/get-changed-params.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/react/get-children.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/react/get-params.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/react/init-swiper.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/react/loop.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/react/params-list.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/react/swiper.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/react/swiper-react.d.ts
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/react/swiper-react.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/react/swiper-slide.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/react/update-swiper.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/react/use-isomorphic-layout-effect.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/react/utils.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/react/virtual.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/README.md
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/shared/classes-to-selector.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/shared/create-element-if-not-defined.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/shared/create-shadow.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/shared/dom.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/shared/effect-init.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/shared/effect-target.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/shared/effect-virtual-transition-end.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/shared/get-browser.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/shared/get-device.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/shared/get-support.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/shared/utils.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/svelte/get-changed-params.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/svelte/get-params.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/svelte/init-swiper.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/svelte/params-list.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/svelte/swiper-slide.svelte
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/svelte/swiper.svelte
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/svelte/swiper-svelte.d.ts
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/svelte/swiper-svelte.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/svelte/update-swiper.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/svelte/utils.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/swiper-bundle.css
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/swiper-bundle.esm.browser.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/swiper-bundle.esm.browser.js.map
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/swiper-bundle.esm.browser.min.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/swiper-bundle.esm.browser.min.js.map
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/swiper-bundle.esm.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/swiper-bundle.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/swiper-bundle.js.map
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/swiper-bundle.min.css
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/swiper-bundle.min.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/swiper-bundle.min.js.map
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/swiper.d.ts
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/swiper.esm.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/swiper.less
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/swiper.min.css
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/swiper.scss
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/swiper-vars.less
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/swiper-vars.scss
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/types/index.d.ts
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/types/modules/a11y.d.ts
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/types/modules/autoplay.d.ts
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/types/modules/controller.d.ts
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/types/modules/effect-cards.d.ts
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/types/modules/effect-coverflow.d.ts
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/types/modules/effect-creative.d.ts
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/types/modules/effect-cube.d.ts
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/types/modules/effect-fade.d.ts
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/types/modules/effect-flip.d.ts
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/types/modules/free-mode.d.ts
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/types/modules/grid.d.ts
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/types/modules/hash-navigation.d.ts
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/types/modules/history.d.ts
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/types/modules/keyboard.d.ts
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/types/modules/lazy.d.ts
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/types/modules/manipulation.d.ts
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/types/modules/mousewheel.d.ts
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/types/modules/navigation.d.ts
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/types/modules/pagination.d.ts
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/types/modules/parallax.d.ts
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/types/modules/public-api.d.ts
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/types/modules/scrollbar.d.ts
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/types/modules/thumbs.d.ts
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/types/modules/virtual.d.ts
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/types/modules/zoom.d.ts
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/types/shared.d.ts
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/types/swiper-class.d.ts
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/types/swiper-events.d.ts
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/types/swiper-options.d.ts
%{_datadir}/AnycubicSlicerNext/resources/web/include/swiper/vue/*
%{_datadir}/AnycubicSlicerNext/resources/web/include/viewer/viewer.css
%{_datadir}/AnycubicSlicerNext/resources/web/include/viewer/viewer-jquery.min.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/viewer/viewer.js
%{_datadir}/AnycubicSlicerNext/resources/web/include/viewer/viewer.min.css
%{_datadir}/AnycubicSlicerNext/resources/web/model/css/dark.css
%{_datadir}/AnycubicSlicerNext/resources/web/model/img/*
%{_datadir}/AnycubicSlicerNext/resources/web/model/index.html
%{_datadir}/AnycubicSlicerNext/resources/web/model/model.css
%{_datadir}/AnycubicSlicerNext/resources/web/model/model.js
%{_datadir}/AnycubicSlicerNext/resources/web/model/test.js
%{_datadir}/applications/AnycubicSlicer.desktop

%changelog
* Wed Apr 29 2026 Thomas Bittermann <pufferbrater@cobonet.de> - 1.3.9.4-1
- Updated to version 1.3.9.4
- converted from 1.3.96_20260319_224609 deb packages

* Fri Mar 27 2026 Thomas Bittermann <thomas@cobonet.de> - 1.3.96-3
- converted from 1.3.96-20260131_153250 deb packages

* Wed Feb 18 2026 Thomas Bittermann <thomas@cobonet.de> - 1.3.96-2
- converted from 1.3.96_20260218 deb packages

* Tue Jan 27 2026 Thomas Bittermann <thomas@cobonet.de> - 1.3.995-2
- converted from 1.3.995_20260127 deb packages

